version: 2
updates:
  - package-ecosystem: "github-actions"
    directories: ["/", ".github/actions/*/*.yml", ".github/actions/*/*.yaml", "action.yml", "action.yaml", "actions/*/*.yml", "actions/*/*.yaml"]
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directories: ["tests/deps_files"]
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: all
    groups:
      pip:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"

  - package-ecosystem: "uv"
    directories: ["/"]
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: all
    groups:
      uv:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"

# custom updates for .tools directory
  - package-ecosystem: "gomod"
    directories: ["/.tools"]
    allow:
      - dependency-type: indirect
    schedule:
      interval: "monthly"
    groups:
      gomod-tools:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
