repos:
  - repo: https://github.com/fredrikaverpil/creosote
    rev: v3.1.1
    hooks:
      - id: creosote
        args:
          - --venv=.venv
          - --path=src
          - --deps-file=pyproject.toml
          - --section=project.dependencies
