repos:
  - repo: https://github.com/fredrikaverpil/creosote
    rev: 3.1.2
    hooks:
      - id: creosote
        args:
          - '--venv=.venv'
          - '--path=src'
          - '--deps-file=pyproject.toml'
          - '--section=project.dependencies'
