PREREQ_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'impersonate',
    'stronghold',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'ajax_select',
    'django_object_actions',
    'mail_templated',
    'gunicorn',
    'import_export',
    'storages',
]

PROJECT_APPS = [
    'ebbs',
    'events',
    'security',
    'shared',
    'staff',
]
INSTALLED_APPS = PREREQ_APPS + PROJECT_APPS
# INSTALLED_APPS = [
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.sites',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'impersonate',
#     'stronghold',
#     'django.contrib.admin',
#     'django.contrib.admindocs',
#     'ajax_select',
#     'django_object_actions',
#     'mail_templated',
#     'gunicorn',
#     'import_export',
#     'storages',
#     'ebbs',
#     'events',
#     'security',
#     'shared',
#     'staff',
# ]
