name: Feature request
description: File a feature request
# title: "[Feature request]: "
labels: ["enhancement"]
# assignees:
#   - fredrikaverpil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time suggest improvements to Creosote!

  - type: textarea
    id: feature-request
    attributes:
      label: What feature request would you like to suggest?
    validations:
      required: true
