name: Feature request
description: File a feature request
# title: "[Feature request]: "
labels: ["enhancement"]
# assignees:
#   - fredrikaverpil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time suggest improvements to Creosote!

  - type: textarea
    id: feature-request
    attributes:
      label: What feature request would you like to suggest?
    validations:
      required: true

  - type: textarea
    id: backwards-compatibility
    attributes:
      label: Will the feature request break backwards compatibility?
      description: If yes, please explain how important this feature is for you.
    validations:
      required: true
