// Code generated by pocket. DO NOT EDIT.
// To configure tasks, edit Config.AutoRun and Config.ManualRun in config.go.
// See: https://github.com/fredrikaverpil/pocket#configuration

package main

import "github.com/fredrikaverpil/pocket/tasks"

func main() {
	tasks.Run(Config)
}
